In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('pima-indians-diabetes.csv' , names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'])
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [4]:
data.isnull()

preg   plas   pres   skin   test   mass   pedi    age  class
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
763  False  False  False  False  False  False  False  False  False
764  False  False  False  False  False  False  False  False  False
765  False  False  False  False  False  False  False  False  False
766  False  False  False  False  False  False  False  False  False
767  False  False  False  False  False  False  False  False  False

[768 rows x 9 columns]

In [5]:
data.isnull().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [6]:
data.isna().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

"Mean Imputation for Handling Missing or Zero Values in Data Preprocessing"

In [7]:
skines = data[data['skin'] == 0]
skines

preg  plas  pres  skin  test  mass   pedi  age  class
2       8   183    64     0     0  23.3  0.672   32      1
5       5   116    74     0     0  25.6  0.201   30      0
7      10   115     0     0     0  35.3  0.134   29      0
9       8   125    96     0     0   0.0  0.232   54      1
10      4   110    92     0     0  37.6  0.191   30      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
757     0   123    72     0     0  36.3  0.258   52      1
758     1   106    76     0     0  37.5  0.197   26      0
759     6   190    92     0     0  35.5  0.278   66      1
762     9    89    62     0     0  22.5  0.142   33      0
766     1   126    60     0     0  30.1  0.349   47      1

[227 rows x 9 columns]

In [8]:
data['skin'].mean()

20.536458333333332

In [9]:
data_mean = data[data['skin'] !=0]['skin'].mean()

In [10]:
data.replace({'skin':0}, data_mean , inplace=True)

In [11]:
data['test'].mean()

79.79947916666667

In [12]:
data[data['test']!= 0]['test'].mean()

155.5482233502538

In [13]:
test_mean = data[data['test'] !=0]['test'].mean()

In [14]:
data.replace({'test':0}, test_mean , inplace=True)

In [23]:
data.replace({'test':0 , 'skin':0}, np.nan , inplace=True)

In [24]:
data

preg  plas  pres      skin        test  mass   pedi  age  class
0       6   148    72  35.00000  155.548223  33.6  0.627   50      1
1       1    85    66  29.00000  155.548223  26.6  0.351   31      0
2       8   183    64  29.15342  155.548223  23.3  0.672   32      1
3       1    89    66  23.00000   94.000000  28.1  0.167   21      0
4       0   137    40  35.00000  168.000000  43.1  2.288   33      1
..    ...   ...   ...       ...         ...   ...    ...  ...    ...
763    10   101    76  48.00000  180.000000  32.9  0.171   63      0
764     2   122    70  27.00000  155.548223  36.8  0.340   27      0
765     5   121    72  23.00000  112.000000  26.2  0.245   30      0
766     1   126    60  29.15342  155.548223  30.1  0.349   47      1
767     1    93    70  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]

In [25]:
from sklearn.impute import KNNImputer

In [26]:
imputer = KNNImputer(n_neighbors=3)
data = imputer.fit_transform(data)

In [27]:
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
scaler = MinMaxScaler(feature_range=(0,1))
data = scaler.fit_transform(data)

In [30]:
data

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        1.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        0.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        1.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        0.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        1.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        0.        ]])

In [31]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()
data = scaler.fit_transform(data)

In [34]:
data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.46849198,
         1.4259954 ,  1.36589591],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.36506078,
        -0.19067191, -0.73212021],
       [ 1.23388019,  1.94372388, -0.26394125, ...,  0.60439732,
        -0.10558415,  1.36589591],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.68519336,
        -0.27575966, -0.73212021],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.37110101,
         1.17073215,  1.36589591],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.47378505,
        -0.87137393, -0.73212021]])